const text = {
  "hero.badge": "Available for freelance",
  "hero.title.hi": "Hi, I'm",
  "hero.role": "Web Developer - Frontend Engineer - UI Enthusiast",
  "hero.intro":
    "BCA student passionate about building modern, responsive web experiences with React, Next.js, and Tailwind CSS. I turn ideas into clean, performant interfaces.",
  "hero.hire": "Hire Me",
  "hero.resume": "Download Resume",
  "hero.contact": "Contact Me",
  "hero.stat.projects": "Projects",
  "hero.stat.skills": "Skills",
  "hero.stat.years": "Year coding",
  "hero.badge.react": "React - Next.js",
  "hero.badge.ui": "UI / UX",
  "typing.1": "I build modern websites.",
  "typing.2": "I craft delightful UI.",
  "typing.3": "I love React & Next.js.",
  "typing.4": "I turn ideas into pixels.",
  "typing.5": "Let's build something great.",
  "about.eyebrow": "About Me",
  "about.title": "A quick intro",
  "about.who.title": "Who I am",
  "about.who.body":
    "I'm Gourav Takk, a motivated BCA student from Jodhpur with a strong interest in web development and modern frontend technologies. I love crafting clean, responsive interfaces and translating ideas into delightful user experiences.",
  "about.goal.title": "Career Objective",
  "about.goal.body":
    "Seeking opportunities to enhance my technical skills and gain practical experience by contributing to real-world projects using React.js, Next.js, and Tailwind CSS.",
  "about.card.education": "Education",
  "about.card.location": "Location",
  "about.card.certified": "Certified",
  "skills.eyebrow": "Skills",
  "skills.title": "What I work with",
  "skills.sub": "Tech I use to build modern web experiences.",
  "projects.eyebrow": "Projects",
  "projects.title": "Selected work",
  "projects.sub": "A peek at things I've built recently.",
  "project.1.title": "SaaS Landing Page",
  "project.1.desc": "A high-converting landing page with smooth GSAP animations and a glassmorphic hero.",
  "project.2.title": "E-Commerce UI",
  "project.2.desc": "Responsive product catalogue with cart, filters and clean checkout flow.",
  "project.3.title": "Portfolio v1",
  "project.3.desc": "A previous personal portfolio built with HTML, CSS, JavaScript and Bootstrap.",
  "project.4.title": "Task Manager App",
  "project.4.desc": "A productivity app with drag-and-drop boards and persistent local storage.",
  "project.live": "Live Demo",
  "project.github": "GitHub",
  "exp.eyebrow": "Journey",
  "exp.title": "Experience & Education",
  "timeline.1.year": "2024 - Present",
  "timeline.1.title": "BCA, OSSC College",
  "timeline.1.desc": "Bachelor of Computer Applications - currently in 2nd semester.",
  "timeline.2.year": "2024",
  "timeline.2.title": "WsCube Tech - Web Development",
  "timeline.2.desc": "Completed full web development course covering HTML, CSS, JS, React.",
  "timeline.3.year": "2024 - Present",
  "timeline.3.title": "Freelance Projects",
  "timeline.3.desc": "Built multiple responsive sites and learned Git/GitHub workflow.",
  "services.eyebrow": "Services",
  "services.title": "What I can do for you",
  "service.1.title": "Web Development",
  "service.1.desc": "End-to-end websites with modern stacks and best practices.",
  "service.2.title": "Frontend Development",
  "service.2.desc": "Pixel-perfect React & Next.js interfaces, fully responsive.",
  "service.3.title": "Backend Development",
  "service.3.desc": "REST APIs and integrations using Node.js fundamentals.",
  "service.4.title": "Website Design",
  "service.4.desc": "Clean, modern UI design with attention to typography and spacing.",
  "test.eyebrow": "Testimonials",
  "test.title": "Kind words from clients",
  "test.1.text": "Gourav delivered a beautifully clean website and was super responsive to feedback. Highly recommended!",
  "test.2.text": "Great eye for detail and turns Figma into clean code very quickly. A pleasure to collaborate with.",
  "test.3.text": "Reliable, quick learner, and his frontend skills with React and Tailwind are solid.",
  "test.role.1": "Startup Founder",
  "test.role.2": "Designer",
  "test.role.3": "Product Manager",
  "contact.eyebrow": "Contact",
  "contact.title": "Let's build something together",
  "contact.sub": "Have a project in mind? Drop a message.",
  "contact.label.email": "Email",
  "contact.label.phone": "Phone",
  "contact.label.location": "Location",
  "contact.placeholder.name": "Your name",
  "contact.placeholder.email": "Your email",
  "contact.placeholder.phone": "Your phone number",
  "contact.placeholder.subject": "Subject",
  "contact.placeholder.message": "Tell me about your project...",
  "contact.send": "Send Message",
  "contact.sending": "Sending...",
  "contact.error.fix": "Please fix the errors before submitting.",
  "contact.error.name.required": "Name is required",
  "contact.error.name.letters": "Name can only contain letters and spaces",
  "contact.error.email.required": "Email is required",
  "contact.error.email.valid": "Please enter a valid email address",
  "contact.error.phone.required": "Phone number is required",
  "contact.error.phone.valid": "Phone number must contain only digits (7-15)",
  "contact.error.subject.required": "Subject is required",
  "contact.error.message.required": "Message is required",
  "contact.success": "Message sent! I'll get back to you soon.",
  "contact.fail": "Could not send message. Please try again later.",
  "footer.rights": "All rights reserved.",
};

export function useContent() {
  return {
    t: (key) => text[key] ?? key,
  };
}

